config/routes.rb
Rails.application.routes.draw do
  resources :report

root 'pages#index'
match '/report/:id/:pid', :to => 'report#bypage', :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ }   , via:[:get]
match '/test'          , :to => 'report#test'                                    , via:[:get]
match '/report/:id/hx' , :to => 'report#hx'   , :constraints => { :pid => /[0-9]+(\%7C[0-9]+)*/ }    , via:[:get]
match '/crawler'       , :to => 'pages#configCrawler'                            , via:[:get]
match '/crawler'       , :to => 'pages#submitCrawl', :as => :sites               , via:[:post]
match '/index'         , :to => 'pages#index'                                    , via:[:get]
match '/crawler/:id'       , :to => 'pages#recrawl'                              , via:[:get]
match '/crawler/mobile/:id'       , :to => 'pages#recrawl2'                              , via:[:get]
match '/report/ranks/:id'       , :to => 'report#ranks'                          , via:[:get]
match '/report/ranks/:id'       , :to => 'report#ranks_add'                      , via:[:post]
match '/report/ranks/:id'       , :to => 'report#ranks_destroy'                  , via:[:delete]
match '/report/ranks/:id/export', :to => 'report#ranks_textfile'                 , via:[:get] 
match '/report/ranks/:id/csv', :to => 'report#ranks_csv'                 , via:[:get] 
match '/report/ranks/:id', :to => 'report#ranks_update'                 , via:[:patch] 
match '/report/ranks/:id/:pid'       , :to => 'report#chart', :constraints => { :pid => /[0-9]+(\%7C[0-9]+)*/ }                         , via:[:get]
match '/report'       , :to => 'report#index', :as => :list                      , via:[:get]
match '/report/print/:id', :to => 'report#download'                                  , via:[:get]
match '/report/print-https/:id', :to => 'report#download_https'                                  , via:[:get]
match '/report/print-image/:id', :to => 'report#download_image'                                  , via:[:get]
match '/report/print-https-image/:id', :to => 'report#download_https_image'                                  , via:[:get]
match '/report/print-mobile/:id', :to => 'report#download_mobile'                                  , via:[:get]
match '/report/print-https-mobile/:id', :to => 'report#download_https_mobile'                                  , via:[:get]
match '/report/test/design', :to => 'report#design', via:[:get]

end

app/controllers/report_controller.rb
# -*- coding: utf-8 -*-
require 'csv'

class ReportController < ApplicationController
			IMAGES_PATH = File.join(Rails.root, "public")
	def bypage
#		p = Site.find(params[:id]).pages.all.where(id:params[:pid]).first
		@Page = Site.find(params[:id]).pages.all.where(id:params[:pid]).all
		@Site = Site.find(params[:id])
	end
	def initialize
		super
		@HX_ORDER 			= 1              # Erreur d'ordonancement
		@HX_DUPLICATE 		= 2              # Duplicatat de balise <hx> sut le site
		@HX_DIFF 			= 3              # </h1> <h3> 
		@PARSER 			= 4            	 # Erreur de Nokogiri
		@TITLE_DUPLICATE 	= 5				 # Duplicatat de titre
		@IMG_NOALT 			= 6				 # Pas de alt sur une image
		@TITLE_LENGTH 		= 7 			 # Titre trop long
		@EXTERNAL_FOLLOW    = 8		         # Lien externe sans nofollow
		@NO_HREF            = 9     	     # balise <a> sans href
		@BAD_LINK           = 10         	 # Lien mal formé qui fait planter le parseur uri
		@DEAD_LINK          = 11         	 # Ein 404
		@TITLE_LENGTH_SHORT = 12           #Title trop long
	end
	def show
		begin	
			@site = Site.find(params[:id])
		rescue
			redirect_to root_path
		end
	end
	def hx
		if (@site = Site.find(params[:id])) == nil
			redirect_to root_path
		end
	end
	def img
	end
	def test
		# Juste parce qu'on aime coder moche <3
		# Owi !!!
	end
	def ranks
		@site = Site.find(params[:id])
		@ranks = @site.queries
	end
	def ranks_add
		query = params[:q].chomp
		puts query
		id = params[:id]
		query.gsub! "\r\n", "\" \""
		spawn("ruby rank.rb " + id.to_s + " \"" + query.to_s + "\"")
		redirect_to :back
	end
	def ranks_destroy
		Query.find(params[:id]).destroy
		redirect_to :back
		flash[:notice] = "Pouette"
	end
	def index
		@sites = Site.all
	end
	def destroy
		Site.find(params[:id]).destroy
		redirect_to :back
	end
	#@Page = Site.find(params[:id]).pages.all.where(id:params[:pid]).all
	def ranks_textfile
		site = Site.find(params[:id])
		get_content = ""
		site.queries.each do |t|
			get_content = get_content + t.query + "\r\n"
		end
		k_name = "export_keyword_" + site.id.to_s
	  	send_data get_content,:type => 'text',:disposition => "attachment; filename=#{k_name}"
	end
	def ranks_update
		site = Site.find(params[:id])
		id = params[:id]
		update_content = ""
		site.queries.each do |t|
			update_content = update_content + " \"" + t.query + "\""
		end
		puts update_content
		puts id.to_s
		spawn("ruby rank.rb " + id.to_s + update_content)
		redirect_to :back
	end
	def ranks_csv
   		site = Site.find(params[:id])
  		keywords_csv = CSV.generate(:col_sep => "\t") do |csv|
  			csv << [site.url]
		    csv << ["Requete", "Rang", "Meilleur", "Date"]
		 	site.queries.each do |key|
		      csv << [key.query, key.positions.last.pos, key.positions.minimum(:pos), key.positions.last.updated_at.strftime("%Y-%m-%d")]
		    end
		  end
		send_data keywords_csv, :type => 'text/xls', :filename => 'export.xls'
	end
	def chart
		@keyword = Site.find(params[:id]).queries.all.where(id:params[:pid]).first
		posi = []
		date = []
		@keyword.positions.each do |t|
			posi.push(t.pos)
			date.push(t.created_at.to_time.strftime("%Y-%m-%d"))
		end
		@chart = LazyHighCharts::HighChart.new('graph') do |f|
			f.title(:text => "Positionnement")
			f.xAxis(:categories => date)
			f.series(:name => "Positions", :yAxis => 0, :data => posi)

			f.yAxis [
			{:title => {:text => "positions", :margin => 70} },
			]

			f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
			f.chart({:defaultSeriesType=>"line"})
		end
	end
	def download
		site = Site.find(params[:id])
          site.sitemap.str = site.sitemap.str + '.xml' unless site.sitemap.str.to_s.end_with? '.xml'
		data = open(IMAGES_PATH + "/" + site.sitemap.str.to_s)
        	send_data data.read, type: 'application/xml', filename: "Sitemap-" + site.url + ".xml"
	end
	def download_https
		site = Site.find(params[:id])
          spawn('python2 ' + Rails.root.to_s + '/https.py -i ' + Rails.root.to_s + '/public/')
          data = open(IMAGES_PATH + "/" + site.sitemap.str.to_s.split('.')[0] + 'https.xml')
		send_data data.read, type: 'application/xml', filename: "Sitemap-" + site.url + "https.xml"
	end
	def download_image
		site = Site.find(params[:id])
		data = open(IMAGES_PATH + "/" + site.sitemap.str.to_s.split('.')[0] + '-image.xml')
		send_data data.read, type: 'application/xml', filename: "Sitemap-" + site.url + "-image.xml"
	end
	def download_https_image
		site = Site.find(params[:id])
          spawn('python2 ' + Rails.root.to_s + '/https.py -i ' + Rails.root.to_s + '/public/')
		data = open(IMAGES_PATH + "/" + site.sitemap.str.to_s.split('.')[0] + '-imagehttps.xml')
		send_data data.read, type: 'application/xml', filename: "Sitemap-" + site.url + "https-image.xml"
	end
	def download_mobile
		site = Site.find(params[:id])
		data = open(IMAGES_PATH + "/" + site.sitemap.str.to_s.split('.')[0] + '.xml')
		send_data data.read, type: 'application/xml', filename: "Sitemap-" + site.url + "-mobile.xml"
	end
	def download_https_mobile
		site = Site.find(params[:id])
          spawn('python2 ' + Rails.root.to_s + '/https.py -i ' + Rails.root.to_s + '/public/')
		data = open(IMAGES_PATH + "/" + site.sitemap.str.to_s.split('.')[0] + 'https.xml')
		send_data data.read, type: 'application/xml', filename: "Sitemap-" + site.url + "https-mobile.xml"
	end
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/report/bypage.html.erb
<% content_for :head do %>
<div id="Menu-top">
	<ul>
		<div id="Menu-top-li">
			<li><%= link_to "Liste des rapports", list_path %></li>
			<li><%= link_to "Index", root_path %></li>
			<li><%= link_to "Ajouter un site", crawler_path %></li>
			<li><%= link_to "Retour", "../" + @Site.id.to_s %></li>
		</div>	
	</ul>
</div>
<% end %>
<center><h2> <a id= "linkbypage" href ="<%= @Page.first.url.to_s %>"><%= @Page.first.url.to_s %></a> </h2></center>

<div id="print_bupage">
	<%= link_to '', '', :onclick => 'window.print();return false;'%>
</div>
Compte rendu détaillé : <br /><br />

<div id="bypage_error">
<% @Page.each do |p| %>
	<div id ="bypage_balises">
		Erreurs balise hx : 
		<font color=<% if p.seoerrors.where(code: [@HX_ORDER, @HX_DUPLICATE, @HX_DIFF]).count > 0 %>"red"
		<% else %>
			"green"
		<% end %>>
			<%= p.seoerrors.where(code: [@HX_ORDER, @HX_DUPLICATE, @HX_DIFF]).count %>
		</font>
		<% if p.seoerrors.where(code: [@HX_ORDER, @HX_DUPLICATE, @HX_DIFF]).count > 0 %>
			<% p.seoerrors.where(code: [@HX_ORDER, @HX_DUPLICATE, @HX_DIFF]).each do |e| %>
				<br />
				<li>Erreur ligne : <%= e.line %> | <font color ="red"><%=  e.desc.to_s.force_encoding("UTF-8") %></font></li>
			<% end %>
		<% end %>
		<br />
		Balises : <br />
			<% p.hxes.each do |h| %>
				<li> Balise n° <%= p.hxes.index(h) + 1 %> > h<%= h.x %> <%= h h.content.force_encoding("UTF-8") %></li>
			<% end %>
	</div>
	<% if p.seoerrors.where(code: @TITLE_LENGTH).count > 0 %> <font color="red"> 
		Title trop long<br />
		<% p.seoerrors.where(code: @TITLE_LENGTH).each do |i| %>
		 Taille : <%= i.desc.length %> caractères<br />
		 <%= i.desc.force_encoding('UTF-8') %><br />
		 <%end%>
	 	</font>
	<% else %>
		<font color="green">Taille du title valide</font><br />
	<% end %>
	<br />
	<% if p.seoerrors.where(code: @DEAD_LINK).count > 0 %>
		<font color="red"> 
		Erreur 404 :<br /><br />
		<% p.seoerrors.where(code: @DEAD_LINK).each do |i| %>
		 <%= link_to i.desc, i.desc, target: '_blank', style:'color:red;' %><br />
		 <%end%>
	 	</font>
	<% end %>
	<br />
	Images sans alt : 
	<% if p.seoerrors.where(code: @IMG_NOALT).count > 0 %> <font color="red"> 
		<%= p.seoerrors.where(code: @IMG_NOALT).count %>
		<% p.seoerrors.where(code: @IMG_NOALT).each do |i| %>
		 <li> <%= i.desc.force_encoding('UTF-8') %> ligne  :<%= i.line %></li>
		 <%end%>
	 	</font>
	<% else %>
		<font color="green">0</font><br />
	<% end %>
	<br />
	Liens sans nofollow : 
	<% if p.seoerrors.where(code: @EXTERNAL_FOLLOW).count > 0 %> <font color="purple"> 
		<%= p.seoerrors.where(code: @EXTERNAL_FOLLOW).count %>
		<% p.seoerrors.where(code: @EXTERNAL_FOLLOW).each do |i| %>
		 	<li> <%= i.desc.force_encoding('UTF-8') %> ligne  :<%= i.line %></li>
		 <%end%>
	 	</font>
	<% else %>
		<font color="green">0</font><br />
	<% end %>
	<br />
	Balise "a" sans href : 
	<% if p.seoerrors.where(code: @NO_HREF).count > 0 %> <font color="red"> 
		<%= p.seoerrors.where(code: @NO_HREF).count %>
		<% p.seoerrors.where(code: @NO_HREF).each do |i| %>
		 	<li> <%= i.desc.force_encoding('UTF-8') %> ligne : <%= i.line %></li>
		 <%end%>
	 	</font>
	<% else %>
		<font color="green">0</font><br />
	<% end %>
	<br />
	Erreurs HTML : 
	<% if p.seoerrors.where(code: @PARSER).count > 0 %> <font color="red"> 
		<%= p.seoerrors.where(code: @PARSER).count %>
	<% end %>
	</center><br/>
	<%  p.seoerrors.where(code: @PARSER).each do |e| %>
	<li>	<%= e.desc.force_encoding('UTF-8') %>  ligne : <%= e.line %></li>
	<% end %>
	</font>
	<br />
	Mauvais liens : 
	<% if p.seoerrors.where(code: @BAD_LINK).count > 0 %> <font color="red"> 
		<%= p.seoerrors.where(code: @BAD_LINK).count %>
	<% end %>
	</center><br/>
	<%  p.seoerrors.where(code: @BAD_LINK).each do |e| %>
	<li>	<%= e.desc.force_encoding('UTF-8') %>  ligne <%= e.line %></li>
	<% end %>
	</font>
	<br />
	Title Dupliqué : 
	<% if p.seoerrors.where(code: @TITLE_DUPLICATE).count > 0 %> <font color="red"> 
		<%= p.seoerrors.where(code: @TITLE_DUPLICATE).count %>
		<% p.seoerrors.where(code: @TITLE_DUPLICATE).each do |i| %>
		 <li> <%= i.desc.force_encoding('UTF-8') %> </li>
		 <%end%>
	<% else %>
		0
	<% end %>
	</font>
<% end %>
</div>

app/views/report/chart.html.erb
<% content_for :head do %>
<div id="Menu-top">
	<ul>
		<div id="Menu-top-li">
			<li><%= link_to "Liste des rapports", list_path %></li>
			<li><%= link_to "Index", root_path %></li>
			<li><%= link_to "Ajouter un site", crawler_path %></li>
			<li><%= link_to "Retour", "../" + params[:id] %></li>
		</div>
	</ul>
</div>
<% end %>

<%= high_chart("some_id", @chart) %>

app/views/report/design.html.erb
<div id="design_header">

	<ul>
		<div id="li_design_header">
			<li><%= link_to "Home", "" %></li>
			<li><%= link_to "Services", "" %></li>
			<li><%= link_to "About", "" %></li>
			<li><%= link_to "Contacts", "" %></li>
		</div>
	</ul>
</div>
<div id="logo8"> </div>

app/views/report/hx.html.erb
<h1> Outil d'analyse des balises hx </h1>


<center>
	
	<select name="page">
	<% @site.pages.each do |p| %>
	  <option <% if [p.id] & @hxFiles != nil.to_a %> style="background:red;" <% end %> value=<%= p.url%>><%= p.url.split('/').last.to_s %></option>
	<%end%>
	</select>

app/views/report/index.html.erb
<% content_for :head do %>
<div id="Menu-top">
	<ul>
		<div id="Menu-top-li">
			<li><%= link_to "Ajouter un site", crawler_path %></li>
			<li><%= link_to "Index", root_path %></li>
		</div>
	</ul>
</div>
<% end %>

<div id="report_index_link">
<ul>
<% @sites.each do |s| %>
	<div id="report_index_block">
		<div id="img_delete_report">
			<%= link_to "", "/report/" + s.id.to_s, method: :delete %>
		</div>
		<div id="img_refresh_report">
			<%= link_to "", crawler_path + "/" + s.id.to_s, method: :get %>
		</div>
		<div id="img_sitemap_mobile">
		  <%= link_to "", crawler_path + "/mobile/" + s.id.to_s %>
		</div>
		
		<div id="img_sitemap_report">
			<% unless s.sitemap.nil? %>
				<%= link_to "Sitemap HTTP", "report/print/" + s.id.to_s, method: :get  %>
			<% end %>
		</div>
		<div id="img_sitemap_https_report">
			<% unless s.sitemap.nil? %>
				<%= link_to "Sitemap HTTPS", "report/print-https/" + s.id.to_s, method: :get  %>
			<% end %>
		</div>
		<div id="img_sitemap_image_report">
			<% unless s.sitemap.nil? %>
				<%= link_to "Sitemap Image HTTP", "report/print-image/" + s.id.to_s, method: :get  %>
			<% end %>
		</div>
		<div id="img_sitemap_image_https_report">
			<% unless s.sitemap.nil? %>
				<%= link_to "Sitemap image HTTPS", "report/print-https-image/" + s.id.to_s, method: :get  %>
			<% end %>
		</div>

		<div id="img_sitemap_mobile_report">
				<%= link_to "Sitemap Mobile", "report/print-mobile/" + s.id.to_s %>
		</div>
		<div id="img_sitemap_mobile_https_report">
			<% unless s.sitemap.nil? %>
				<%= link_to "Sitemap Mobile HTTPS", "report/print-https-mobile/" + s.id.to_s, method: :get  %>
			<% end %>
		</div>
			<div id="img_search_report">
			<%= link_to "", list_path + "/ranks/" +  s.id.to_s %>
		</div>
		<li class="index_li_link"><%= link_to s.url, report_path(s.id) %></li>
		<span id="txt">Id : <%= s.id %></span><br/>
		<span id="txt">Crawl le : <%= s.created_at.to_s(:short) %></span><br/>
		<span id="txt">Mis à jour le : <%= s.updated_at.to_s(:short) %></span><br/>
		<span id="txt">Nombre de pages : <%= s.pages.count %></span><br/>
		<span id="txt"> <% if s.processing  == true %> En cours de crawl <% else %> Crawl fini <% end %> </span><br />
		<span id="txt">Erreurs de balises hx :</span>
		<font color=<% if s.seoerrors.where(code: [1, 2, 3]).count == 0 %> "green" <% else %> "red" <% end %>>
			<% if s.seoerrors.where(code: [1, 2, 3]).count == 0 %>
				Aucune erreur<br />
			<%else%>
				<%= s.seoerrors.where(code: [1, 2, 3]).count %> erreurs<br />
			<% end %>
		</font>
		<span id="txt">Erreurs de 404 :</span>
		<font color=<% if s.seoerrors.where(code: [11]).count == 0 %> "green" <% else %> "red" <% end %>>
			<% if s.seoerrors.where(code: [11]).count == 0 %>
				Aucune erreur<br />
			<%else%>
				<%= s.seoerrors.where(code: [11]).count %> erreurs<br />
			<% end %>
		</font>
		<span id="txt">Nombre d'erreurs html : </span>
		<%= s.seoerrors.where(code: 4).count %><br/>
		<span id="txt">Erreurs sur les title :</span>
		<font color=<% if s.seoerrors.where(code: [7, 12]).count == 0 %> "green" <% else %> "red" <% end %>>
			<% if s.seoerrors.where(code: [7, 12]).count == 0 %>
				Aucune erreur<br />
			<%else%>
				<%= s.seoerrors.where(code: [7, 12]).count %> erreur(s)<br />
			<% end %>
		</font>
	</div>
<% end %>
</ul>
</div>

app/views/report/ranks.html.erb
<% content_for :head do %>
<div id="Menu-top">
	<ul>
		<div id="Menu-top-li">
			<li><%= link_to "Liste des rapports", list_path %></li>
			<li><%= link_to "Index", root_path %></li>
			<li><%= link_to "Ajouter un site", crawler_path %></li>
		</div>
	</ul>
</div>
<% end %>

Id : <%= @site.id %><br />
Url : <%= @site.url %><br />
<br />

<div id="img_print_ranks">
	<%= link_to "", "/report/ranks/" + @site.id.to_s + "/export", method: :get %>
</div>

<div id="img_refresh_ranks">
	<%= link_to "", "/report/ranks/" + @site.id.to_s, method: :patch %>
</div>

<div id="img_csv_ranks">
	<%= link_to "", "/report/ranks/" + @site.id.to_s + "/csv", format: "xls", method: :get %>
</div>

<br /><br /><br /><br />
<%= form_tag("", method: "post") do %>
  <div id="area_ranks">
  	<%= text_area_tag(:q) %>
  </div>
  <% hidden_field_tag(:id, @site.id) %>
  <%= submit_tag("Add") %>
<% end %>

<div id ="rang_balises">
	<% if @ranks.count == 0 %>
		Aucunes position enregistré
	<% else %>
	<table border="1" width="800">
		<tr>
			<td><center>Requete</center></td>
			<td><center>Rang</center></td>
			<td><center>Nb de recherches</center></td>
			<td><center>Meilleur</center></td>
		</tr>
		<% @ranks.each do |p| %>
				<tr>
					<% if p.positions.last.pos == 10000 %>
						<td>
							<div id="img_delete_ranks">
								<%= link_to "", "" + p.id.to_s, method: :delete %>
							</div>
							<%= link_to p.query, "./" + @site.id.to_s + "/" + p.id.to_s %>
						</td>
						<td>
							<center><font color="red">>100</font></center>
						</td>
					<% else %>
						<td>
							<div id="img_delete_ranks">
								<%= link_to "", "" + p.id.to_s, method: :delete %>
							</div>
							<%= link_to p.query, "./" + @site.id.to_s + "/" + p.id.to_s%>
							<div id="img_web_ranks">
								<%= link_to "", "https://www.google.fr/search?q=" + p.query.gsub(' ', '+').to_s, target: "_blank" %>
							</div>
						</td>
						<td>
							<center>
								<%= p.positions.last.pos %>
								<% if p.positions.count(:pos) > 1 %>
									<% pos_prev =  p.positions.limit(p.positions.count(:pos) - 1).last.pos %>
									<% pos_res = pos_prev - p.positions.last.pos %>
									<% if pos_res < 10000 %>
										<% if pos_res < 0 %>
											<font color="red">- <%= pos_res * -1 %></font>
										<% else %>
											<% if pos_res <= 1000 and pos_res != 0 %>
												<font color="green">+ <%= pos_res %></font>
											<% end %>
										<% end %>
									<% end %>
								<% end %>
							</center>
						</td>
					<% end %>
					<td>
						<center><%= p.positions.count(:pos) %></center>
					</td>
					<td>
						<% if p.positions.minimum(:pos) == 10000 %>
							<center><font color="red">Indisponible</font></center>
						<% else %>
							<center><%= p.positions.minimum(:pos) %></center>
						<% end %>
					</td>
				</tr>
		<% end %>
	</table>
	<% end %>
</div>

app/views/report/show.html.erb
<% content_for :head do %>
<div id="Menu-top">
	<ul>
		<div id="Menu-top-li">
			<li><%= link_to "Liste des rapports", list_path %></li>
			<li><%= link_to "Index", root_path %></li>
			<li><%= link_to "Ajouter un site", crawler_path %></li>
		</div>
	</ul>
</div>
<% end %>
<center><h1> Rapport du site <%= @site.name %> </h1> <br /><br />

<!-- Preview des erreurs début -->

Nombre de pages : <%= @site.pages.count %> <br />

Erreurs de balises < hx > :
<font color=<% if @site.seoerrors.where(code: [@HX_ORDER, @HX_DUPLICATE, @HX_DIFF]).count == 0 %> "green" <% else %> "red" <% end %>>
<% if @site.seoerrors.where(code: [@HX_ORDER, @HX_DUPLICATE, @HX_DIFF]).count == 0 %>
	Aucune erreur<br />
<%else%>
	<%= @site.seoerrors.where(code: [@HX_ORDER, @HX_DUPLICATE, @HX_DIFF]).count %> erreurs<br />
<% end %>
</font>
Erreurs de taille sur le Title :
<font color=<% if @site.seoerrors.where(code: [@TITLE_LENGTH]).count + @site.seoerrors.where(code: [@TITLE_LENGTH_SHORT]).count == 0 %> "green" <% else %> "red" <% end %>>
<% if (@site.seoerrors.where(code: [@TITLE_LENGTH]).count + @site.seoerrors.where(code: [@TITLE_LENGTH_SHORT]).count) == 0 %>
	Aucune erreur<br />
<%else%>
	<%= @site.seoerrors.where(code: [@TITLE_LENGTH]).count + @site.seoerrors.where(code: [@TITLE_LENGTH_SHORT]).count %> erreur(s)<br />
<% end %>
</font>
Erreurs HTML :
<font color=<% if @site.seoerrors.where(code: [@PARSER]).count == 0 %> "green" <% else %> "red" <% end %>>
<% if @site.seoerrors.where(code: [@PARSER]).count == 0 %>
	Aucune erreur<br />
<%else%>
	<%= @site.seoerrors.where(code: [@PARSER]).count %> erreurs<br />
<% end %>
</font>
Erreurs d'images sans Alt :
<font color=<% if @site.seoerrors.where(code: [@IMG_NOALT]).count == 0 %> "green" <% else %> "red" <% end %>>
<% if @site.seoerrors.where(code: [@IMG_NOALT]).count == 0 %>
	Aucune erreur<br />
<%else%>
	<%= @site.seoerrors.where(code: [@IMG_NOALT]).count %> erreurs<br />
<% end %>
</font>
Erreurs 404 :
<font color=<% if @site.seoerrors.where(code: [@DEAD_LINK]).count == 0 %> "green" <% else %> "red" <% end %>>
<% if @site.seoerrors.where(code: [@DEAD_LINK]).count == 0 %>
	Aucune erreur<br />
<%else%>
	<%= @site.seoerrors.where(code: [@DEAD_LINK]).count %> erreurs<br />
<% end %>
</font>
<br/>
</center>

<!-- Preview des erreurs fin -->
<br/><br/><br/>
<!-- Listing des pages début -->

<% @site.pages.each do |p| %>
	<div id="bloc_url_show">
		<div id="url_show"><%= link_to URI(p.url.to_s).path, '/report/' + @site.id.to_s + '/' + p.id.to_s %>
		<% if p.seoerrors.where(code: [@DEAD_LINK]).count > 0 %>
			<font color="red">
		 		| Erreurs 404
			</font>
		<% end %>
		</div>
		<div id="error_show">
			<div id="error_show">
				<% if p.seoerrors.where(code: [@HX_ORDER, @HX_DUPLICATE, @HX_DIFF]).count > 0 %>
					<font color="red">
				 		Erreurs balise hx : <%= p.seoerrors.where(code: [@HX_ORDER, @HX_DUPLICATE, @HX_DIFF]).count %>
					</font>
				<%end %>
			</div>
			<div id="error_show_noalt">
				<% if p.seoerrors.where(code: @IMG_NOALT).count > 0 %>
					<font color="red"> 		
				 		Images sans Alt : <%= p.seoerrors.where(code: @IMG_NOALT).count %>
					</font>
				<%end %>
			</div>
			<div id="error_show_titlesize">
				<% if p.seoerrors.where(code: @TITLE_LENGTH).count > 0 %>
					<font color="red"> 
				 		Title trop long : <%= p.seoerrors.where(code: @TITLE_LENGTH).count %>
					</font>
				<%end %>
			</div>
            <div id="error_show_titlesize">
            <% if p.seoerrors.where(code: @TITLE_LENGTH_SHORT).count > 0 %>
                <font color="red">
                  Title trop court : <%= p.seoerrors.where(code: @TITLE_LENGTH_SHORT).count %>
                </font>
            <%end %>
            </div>
			<div id="error_show_html">
				<% if p.seoerrors.where(code: @PARSER).count > 0 %>
					<font color="red">
						Erreurs HTML : <%= p.seoerrors.where(code: @PARSER).count %>
					</font>
				<% end %>
			</div>
			<br/>
		</div>
	</div>
<% end %>


<!-- Listing des pages fin -->

app/views/report/test.html.erb
<h1>toto</h1>
<h3>haha</h3>
<h6>HOHO</h6>
<h3>toto</h3>